resources:
  repositories:
    - repository: azure-sdk-for-js
      type: github
      name: joheredi/azure-sdk-for-js
      endpoint: joheredi
      ref: prototype-external-pipelines

trigger:
  branches:
    include:
      - master
      - release/*
      - hotfix/*

pr:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - hotfix/*

extends:
  template: eng/pipelines/templates/stages/archetype-sdk-external.yml@azure-sdk-for-js
  parameters:
    RepoId: Azure/ms-rest-azure-js
    ServiceDirectory: ms-rest-azure-js
    Artifacts:
      - name: azure-ms-rest-azure-js
        safeName: azuremsrestazurejs
        skipPublishDocMs: true
        skipPublishDocGithubIo: true
        skipUpdatePackageVersion: true
