trigger:
  branches:
    include:
      - master
      - release/*
      - hotfix/*

pr:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - hotfix/*

extends:
  template: https://raw.githubusercontent.com/joheredi/azure-sdk-for-js/prototype-external-pipelines/eng/pipelines/templates/stages/archetype-sdk-external.yml
  parameters:
    ServiceDirectory: ms-rest-js
    Artifacts:
      - name: azure-ms-rest-js
        safeName: azuremsrestjs
